### ISSUE TITLE
Use btcd(Go) rpc server connect error

### ISSUE THREAD

**Issue by Demontf** [priiduneemre/btcd-cli4j#6]
4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
HttpLayerException(super=CommunicationException(super=com.neemre.btcdcli4j.core.http.HttpLayerException: Error #1004004: The operation failed due to an unknown IO exception., code=1004004))
	at com.neemre.btcdcli4j.core.http.client.SimpleHttpClientImpl.execute(SimpleHttpClientImpl.java:66)
	at com.neemre.btcdcli4j.core.jsonrpc.client.JsonRpcClientImpl.execute(JsonRpcClientImpl.java:64)
	at com.neemre.btcdcli4j.core.jsonrpc.client.JsonRpcClientImpl.execute(JsonRpcClientImpl.java:44)
	at com.neemre.btcdcli4j.core.client.BtcdClientImpl.getInfo(BtcdClientImpl.java:323)
	at com.neemre.btcdcli4j.core.client.BtcdClientImpl.<init>(BtcdClientImpl.java:59)
	at T.main(T.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:8334 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.neemre.btcdcli4j.core.http.client.SimpleHttpClientImpl.execute(SimpleHttpClientImpl.java:51)
	... 10 more

**Comment by Demontf** [comment]
I use this repository (https://github.com/btcsuite/btcd/tree/master/docs#NetworkConfig)
